/*
 * This Groovy source file was auto generated by running 'gradle buildInit --type groovy-library'
 * by 'adeady' at '4/17/15 2:14 PM' with Gradle 2.2.1
 *
 * @author adeady, @date 4/17/15 2:14 PM
 */
class Library {
    boolean someLibraryMethod() {
        true
    }
}
