/*
 * This Spock specification was auto generated by running 'gradle init --type groovy-library'
 * by 'adeady' at '4/17/15 2:14 PM' with Gradle 2.2.1
 *
 * @author adeady, @date 4/17/15 2:14 PM
 */

import spock.lang.Specification

class LibraryTest extends Specification{
    def "someLibraryMethod returns true"() {
        setup:
        Library lib = new Library()
        when:
        def result = lib.someLibraryMethod()
        then:
        result == true
    }
}
